name: resq
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.7.7
  firebase_database: ^10.4.0

  intl: ^0.17.0
  google_nav_bar: ^5.0.6
  google_fonts:
  google_maps_flutter: ^2.0.12
  geolocator: ^9.0.1
  geocoding : ^2.0.0
  http: 1.2.1
  flutter_polyline_points: ^2.0.0

  permission_handler: ^10.2.0
  logging: ^1.2.0
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.3.0
  image_picker: ^1.1.2
  flutter_launcher_icons: ^0.13.1
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
     - assets/resq_logo.png
     - assets/hospital_icon.png
     - assets/profile.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
