// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmmrYjGshO06k6l4lwkRniAaq9WJQM5so',
    appId: '1:916233817572:web:bfa4bd10811f06e0000bf1',
    messagingSenderId: '916233817572',
    projectId: 'resq-43d7d',
    authDomain: 'resq-43d7d.firebaseapp.com',
    databaseURL:
        'https://resq-43d7d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'resq-43d7d.appspot.com',
    measurementId: 'G-F2E233RJCQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTG6j7tIvQrts8ZJ0eHQ8dJ4BzwHftxPg',
    appId: '1:916233817572:android:531a4f8025e115bf000bf1',
    messagingSenderId: '916233817572',
    projectId: 'resq-43d7d',
    databaseURL:
        'https://resq-43d7d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'resq-43d7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMi6YTFxw_wHcntXkTS_Rx7Fyj2HWFrCg',
    appId: '1:916233817572:ios:90f7d60e0270a172000bf1',
    messagingSenderId: '916233817572',
    projectId: 'resq-43d7d',
    databaseURL:
        'https://resq-43d7d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'resq-43d7d.appspot.com',
    iosBundleId: 'com.example.resq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMi6YTFxw_wHcntXkTS_Rx7Fyj2HWFrCg',
    appId: '1:916233817572:ios:89dcfa4f3154b81e000bf1',
    messagingSenderId: '916233817572',
    projectId: 'resq-43d7d',
    databaseURL:
        'https://resq-43d7d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'resq-43d7d.appspot.com',
    iosBundleId: 'com.example.resq.RunnerTests',
  );
}
